GET http://localhost:5000/bin/fiveM/server/view/all/json
###
GET http://localhost:5000/bin/fiveM/server/get/abc123
###
GET http://localhost:5000/bin/fiveM/server/view/all/html
###
GET http://localhost:5000/auth/discord/redirect
###
GET http://localhost:5000/bin/fiveM/server/fetch/playhigh.life:30120

###
GET http://localhost:5000/bin/fiveM/server/cfxFetch/a6ev6e
###
GET http://localhost:5000/bin/fiveM/server/61535ed03470a06497550e99/toggleTracking
###
GET http://localhost:5000/
###
GET http://localhost:5000/
###




